
server.port: 1090



spring:
  kafka:
    template:
      default-topic: "devices-topic"
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
   #   transaction-id-prefix: tx
      properties:
        acks: all
        retries: 10
        retry:
          backoff:
            ms: 1000












