server:
  port: 2090

#custom properties to control the error retries
#and recovery retries count
recover.retry.key: "recover.retry.count"
max.recover.retry.count: 2
max.retry.count: 3
max.retry.backoff.ms: 2000
retry.interval.ms: 10000
mytopics:
  main: "devices-topic"
  retry: "devices-topic.RETRY"
  dlt: "devices-topic.DLT"


spring:
  kafka:

    #configure security
    security:
      protocol: "SSL"
    ssl:
      #following config is for configuring the trust store i which the server sent cert is validated
      trust-store-location: file:///E:/MyWork/trainings/Kafka/Code/KafkaTutorials/security-ssl/client-keys/client.truststore.jks
      trust-store-password: kafkassl
      #following config is for configuring the keystire using which client will send the client certificate
      key-store-type: "JKS"
      key-store-location: file:///E:/MyWork/trainings/Kafka/Code/KafkaTutorials/security-ssl/client-keys/client.keystore.jks
      key-store-password: kafkassl
      key-password: kafkassl

    #till here - security
    consumer:
     # enable-auto-commit: true
      #bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      #enable for enabling security
      bootstrap-servers: localhost:10092, localhost:10093,localhost:10094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: device-events-consumer
    #producer is defined here so that it can be used for publishing to
    #retry or dlt during recovery
    producer:
      #bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      #security related.
      bootstrap-servers: localhost:10092, localhost:10093,localhost:10094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#enable for enabling security
    properties:
      ssl.endpoint.identification.algorithm:

---
spring:
  datasource:
    url: jdbc:h2:mem:eventsdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
